id: 72f06ef8241b49b9a0534673f614969e
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_437-The_Practice_Manual_of_Noble_Tara_Kurukulla-v1
  language: en
  author: ''
  volume: {}
